
# The Jaxrs HTTP binding
jaxrsUrl: http://127.0.0.1:7080/jaxrs
  
# The Jaxrs HTTPS port
jaxrsTLSUrl: https://95.179.141.20:7443/jaxrs

# Certificate used for TLS
#jaxrsTLSCrt: /etc/x509/https/tls.crt

# Private key used for TLS
#jaxrsTLSKey: /etc/x509/https/tls.key

# The Keycloak endpoints 
keycloakUrl: http://127.0.0.1:6080/auth
keycloakTLSUrl: https://95.179.141.20:6443/auth
  
# Realm this service belongs to 
keycloakRealm: myrealm
  
# Client for this service 
keycloakClient: myclient

# Credentials for the master realm
keycloakUser: admin
keycloakPassword: admin
