
# The Portal HTTP binding
jaxrsUrl: http://127.0.0.1:7080/jaxrs
  
# The Portal HTTPS port
#jaxrsTLSUrl: https://127.0.0.1:8443/jaxrs

# Certificate used for TLS
#jaxrsTLSCrt: /etc/x509/https/tls.crt

# Private key used for TLS
#jaxrsTLSKey: /etc/x509/https/tls.key

# The Keycloak API endpoint 
keycloakUrl: http://127.0.0.1:6080/auth
  
# Realm this service belongs to 
keycloakRealm: myrealm
  
# Client for this service 
keycloakClient: myclient

# Credentials for the master realm
keycloakUser: admin
keycloakPassword: admin
