
# Keycloak endpoints 
keycloakUrl: http://127.0.0.1:8080/auth
keycloakTLSUrl: https://127.0.0.1:8443/auth
  
# Keycloak realm/client
keycloakRealm: myrealm
keycloakClient: myclient

# Keycloak master credentials
keycloakUser: admin
keycloakPassword: admin

# Jaxrs endpoints 
jaxrsUrl: http://127.0.0.1:8180/jaxrs
jaxrsTLSUrl: https://127.0.0.1:8443/jaxrs

# Potal endpoints
portalUrl: http://127.0.0.1:8280/portal
portalTLSUrl: https://127.0.0.1:8443/portal
  
# Use TLS locations 
useTLS: false
