
# The Jaxrs HTTP binding
portalUrl: http://127.0.0.1:8080/portal
  
# The Jaxrs HTTPS port
portalTLSUrl: https://95.179.141.20:8443/portal

# Certificate used for TLS
#portalTLSCrt: /etc/x509/https/tls.crt

# Private key used for TLS
#portalTLSKey: /etc/x509/https/tls.key

# The Jaxrs HTTP binding
jaxrsUrl: http://127.0.0.1:7080/jaxrs
  
# The Jaxrs HTTPS port
jaxrsTLSUrl: https://95.179.141.20:7443/jaxrs

# The Keycloak endpoints 
keycloakUrl: http://127.0.0.1:6080/auth
keycloakTLSUrl: https://95.179.141.20:6443/auth
  
# Realm this service belongs to 
keycloakRealm: myrealm
  
# Client for this service 
keycloakClient: myclient

# Credentials for the master realm
keycloakUser: admin
keycloakPassword: admin
