
# The Portal HTTP binding
portalHost: 127.0.0.1
portalPort: 8280
  
# The Portal HTTPS port
portalTLSPort: 9443

# Certificate used for TLS
portalTLSCrt: /etc/x509/https/tls.crt

# Private key used for TLS
portalTLSKey: /etc/x509/https/tls.key

# The Keycloak API endpoint 
keycloakUrl: http://127.0.0.1:8180/auth
  
# Realm this service belongs to 
keycloakRealm: myrealm
  
# Client for this service 
keycloakClient: myclient

# Credentials for the master realm
keycloakUser: admin
keycloakPassword: admin
