##################################################################
# H2 
#
jdbcUrl: jdbc:h2:tcp://localhost:9092/fuse;schema=nessus
jdbcUser: keycloak
jdbcPassword: password

##################################################################
# Keycloak
#
keycloakUrl: http://127.0.0.1:8000/auth
keycloakTLSUrl: https://127.0.0.1:8443/auth
  
# Keycloak realm/client
keycloakRealm: myrealm
keycloakClient: myclient

# Keycloak master credentials
keycloakUser: admin
keycloakPassword: admin

##################################################################
# Maven
#
mavenUrl: http://127.0.0.1:8100/maven
mavenTLSUrl: https://127.0.0.1:8443/maven

##################################################################
# Jaxrs
#
jaxrsUrl: http://127.0.0.1:8200/jaxrs
jaxrsTLSUrl: https://127.0.0.1:8443/jaxrs

##################################################################
# Potal
#
portalUrl: http://127.0.0.1:8300/portal
portalTLSUrl: https://127.0.0.1:8443/portal
